### ISSUE TITLE
API 명세의 의도가 명확치 않을 때 코드 작성 방법은?

### ISSUE THREAD

**Issue by JuhyuckHong** [JuhyuckHong/nodejsassignment1#1]
게시글 수정 기능에서,
password를 body로 받는 데, response(error) 코드에 비밀번호 불일치에 대한 명세가 없는 경우,
1. 관리자가 게시글의 password까지 변경하는 상황으로 간주하고 db를 변경
2. 게시글의 password와 body의 password가 일치하는 경우에, title과 content를 수정

게시글 삭제 기능에서,
response(error) 코드에 비밀번호 불일치에 대한 명세가 없는 경우,
1. body로 받은 password 값을 쓰지않고 delete method로 들어오는 params와 일치하는 게시글은 무조건 삭제하도록 구현할지
2. 아니면 비밀번호 비교 후 삭제하는 기능을 구현 할 것인지?

고민됨. 명세가 잘못된 것인지? 혹은 다른 이유인지?

**Comment by diasm3** [comment]
안녕하세요!

정확한 명세가 없어서 고민이 많으셨을거라 생각이 듭니다!
실제 프로젝트에서 흔히 발생하는 명세서의 합의가 잘 이루어 지지 않았을때 이런 놓치는 부분이 생기기도 합니다. 
이럴때는 프론트개발자와 함께 이 예외처리에 대한 명세를 명확히 정의 내려야 합니다.

조건 :  4. 게시글 수정 API
    - API를 호출할 때 입력된 비밀번호를 비교하여 동일할 때만 글이 수정되게 하기
    
1. 관리자가 게시글의 password까지 변경하는 상황으로 간주하고 db를 변경
**-> 보통 이럴때는 401 Error 코드와 함께 Unauthorized 메세지와 함께 리턴됩니다.**  

**-> 게시글 수정에 관한 내용을 보면 비번을 변경하라는 말은 없어보입니다. 따라서 그냥 401에러와 함께 메세지를 리턴하시면 됩니다.
다만 이렇게 명확하지 않고 무엇인가 빠진 부분이 있다면 언제든지 팀원과 함께 확인을 하셔야 합니다.**

2. 게시글의 password와 body의 password가 일치하는 경우에, title과 content를 수정
**-> 조건에 명확히 나와 있기 때문에 이렇게 진행 하는게 맞습니다.**

조건 : 5. 게시글 삭제 API
    - API를 호출할 때 입력된 비밀번호를 비교하여 동일할 때만 글이 삭제되게 하기

1. body로 받은 password 값을 쓰지않고 delete method로 들어오는 params와 일치하는 게시글은 무조건 삭제하도록 구현할지
**-> 조건에 보면 입력된 비밀번호를 비교하여 동일한 때만 글이 삭제되게끔 작성되어 있습니다.**
2. 아니면 비밀번호 비교 후 삭제하는 기능을 구현 할 것인지?
**-> 2번으로 작성하셔야 합니다!**


### 아래 요구사항 입니다!

1. 전체 게시글 목록 조회 API
    - 제목, 작성자명, 작성 날짜를 조회하기
    - 작성 날짜 기준으로 내림차순 정렬하기
2. 게시글 작성 API
    - 제목, 작성자명, 비밀번호, 작성 내용을 입력하기
3. 게시글 조회 API
    - 제목, 작성자명, 작성 날짜, 작성 내용을 조회하기 
    (검색 기능이 아닙니다. 간단한 게시글 조회만 구현해주세요.)
4. 게시글 수정 API
    - API를 호출할 때 입력된 비밀번호를 비교하여 동일할 때만 글이 수정되게 하기
5. 게시글 삭제 API
    - API를 호출할 때 입력된 비밀번호를 비교하여 동일할 때만 글이 삭제되게 하기
6. 댓글 목록 조회
    - 조회하는 게시글에 작성된 모든 댓글을 목록 형식으로 볼 수 있도록 하기
    - 작성 날짜 기준으로 내림차순 정렬하기
7. 댓글 작성
    - 댓글 내용을 비워둔 채 댓글 작성 API를 호출하면 "댓글 내용을 입력해주세요" 라는 메세지를 return하기
    - 댓글 내용을 입력하고 댓글 작성 API를 호출한 경우 작성한 댓글을 추가하기
8. 댓글 수정
    - 댓글 내용을 비워둔 채 댓글 수정 API를 호출하면 "댓글 내용을 입력해주세요" 라는 메세지를 return하기
    - 댓글 내용을 입력하고 댓글 수정 API를 호출한 경우 작성한 댓글을 수정하기
9. 댓글 삭제
    - 원하는 댓글을 삭제하기

**Comment by JuhyuckHong** [comment]
@diasm3 회신 감사합니다. 
조건을 API 명세만 보고 작성하다보니 요구사항을 놓쳤네요. 확인했고, 요구사항 만족하도록 수정 진행하겠습니다.
